# Generated by Django 5.2 on 2025-04-26 21:05

import apps.colaboradores.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargos', '0001_initial'),
        ('empresas', '0001_initial'),
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[apps.colaboradores.validators.valida_nome])),
                ('idade', models.PositiveIntegerField(validators=[apps.colaboradores.validators.valida_idade])),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')])),
                ('telefone', models.CharField(max_length=15, validators=[apps.colaboradores.validators.valida_telefone])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[apps.colaboradores.validators.valida_email])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargos.cargo')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='setores.setor')),
            ],
            options={
                'db_table': 'colaboradores',
            },
        ),
    ]
