# Generated by Django 5.2 on 2025-04-26 21:21

import apps.setores.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='descricao',
            field=models.CharField(max_length=100, validators=[apps.setores.validators.valida_descricao]),
        ),
    ]
