# Generated by Django 5.2 on 2025-04-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0002_alter_setor_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setor',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
    ]
