# Generated by Django 5.2 on 2025-04-26 21:05

import apps.empresas.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, validators=[apps.empresas.validators.valida_nome])),
                ('razao_social', models.CharField(max_length=100, unique=True, validators=[apps.empresas.validators.valida_razao_social])),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[apps.empresas.validators.valida_cnpj])),
                ('inscricao_estadual', models.CharField(max_length=20, unique=True, validators=[apps.empresas.validators.valida_inscricao_estadual])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='EmpresaSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_setores', to='empresas.empresa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_empresas', to='setores.setor')),
            ],
            options={
                'db_table': 'empresa_setores',
                'unique_together': {('empresa', 'setor')},
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='setores',
            field=models.ManyToManyField(related_name='empresas', through='empresas.EmpresaSetor', to='setores.setor'),
        ),
    ]
