# Generated by Django 5.2 on 2025-05-02 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_remove_empresa_setores_delete_empresasetor'),
        ('setores', '0003_alter_setor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaSetor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_setores', to='empresas.empresa')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setor_empresas', to='setores.setor')),
            ],
            options={
                'db_table': 'empresa_setores',
                'unique_together': {('empresa', 'setor')},
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='setores',
            field=models.ManyToManyField(related_name='empresas', through='empresas.EmpresaSetor', to='setores.setor'),
        ),
    ]
