# Generated by Django 5.2 on 2025-05-21 00:14

import apps.empresas.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_empresasetor_empresa_setores'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(max_length=100, null=True, validators=[apps.empresas.validators.valida_email]),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefone',
            field=models.CharField(max_length=15, null=True, validators=[apps.empresas.validators.valida_telefone]),
        ),
    ]
