# Generated by Django 5.2 on 2025-04-26 21:05

import apps.cargos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, validators=[apps.cargos.validators.valida_nome_cargo])),
                ('descricao', models.CharField(max_length=300, validators=[apps.cargos.validators.valida_descricao])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cargos',
            },
        ),
    ]
